name: Test and Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # We are using the prerelase version to get the "check lock command"
        pip install poetry="1.2.0b1"
        poetry config virtualenvs.in-project true
        # Fail the CI if the lock file is not up to date
        poetry lock --check
        poetry install -E calplot -E h5py
    - name: Testing
      run: |
        poetry run doit test
    - name: Linting
      run: |
        poetry run doit -v 0 --continue format_check lint
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
